export const ACTION_TYPE = {
    LOAD_LAST_NEWS: "LOAD_LAST_NEWS",
    LOAD_SINGLE_NEWS: "LOAD_SINGLE_NEWS",
    GET_SINGLE_DATA_LOCAL: "GET_SINGLE_DATA_LOCAL",
    CREATE_NEWS_POST: "CREATE_NEW_POST",
    EDIT_NEWS_POST: "EDIT_NEWS_POST",

    MAKE_CLICK: "MAKE_CLICK",
}


 