export const ACTION_TYPE = {
    LOAD_LAST_NEWS: "LOAD_LAST_NEWS",
    LOAD_SINGLE_NEWS: "LOAD_SINGLE_NEWS",
    GET_SINGLE_DATA_LOCAL: "GET_SINGLE_DATA_LOCAL",
    CREATE_NEWS_POST: "CREATE_NEW_POST",
    EDIT_NEWS_POST: "EDIT_NEWS_POST",

    MAKE_PHOTO_STATE: "MAKE_PHOTO_STATE",

    MAKE_CLICK: "MAKE_CLICK",

    GET_ALL_TASKS: "GET_ALL_TASKS",
    GET_SINGLE_TASKS: "GET_ALL_TASKS",
    UPDATE_SINGLE_TASK: "UPDATE_SINGLE_TASK"
}

export const TASK_ACTION_TYPE = {
    CODING_CODE: "CODING_CODE"
}

export const USER_PROFILE = {
    AUTHORIZATION_USER: "AUTHORIZATION_USER",
    CHANGE_USER_PROFILE: "CHANGE_USER_PROFILE",
    
    ADD_USER_TASK: "ADD_USER_TASK",
    UPDATE_USER_TASK: "UPDATE_USER_TASK",
    COMPLETE_TASK: "COMPLETE_TASK",

    ADD_PHOTO_TO_TASK: "ADD_PHOTO_TOTASK",
    
    ADD_FRIENDS: "ADD_FRIENDS"
}


 